### PR TITLE
Overly reliable send mode and Id parameter for messages

### PR DESCRIPTION
**Pull request by Per6**
it adds an id parameter that is readonly

### CODE REVIEW

**Comment by Per6** [comment]
for some reason some messages recieved by the server give the wrong id, so it isnt finished quite yet

**Comment by Per6** [comment]
i found, that it happens when resending messages, that the id is no longer correct.
Creating a new message, pushing all the data into that one and then sending that seems to not have that problem.
I have no idea how that happens???

**Comment by Per6** [comment]
the change to have the id be unreadable doesnt happen immediately after resending it.
Also i got a workaround by doing this before saving and resending the message:
`public static Message MakeReliableMessageResendable(this Message msg) {
		Message message = Message.Create(MessageSendMode.Reliable, msg.GetId());
		while(msg.UnreadBits >= 8) message.AddByte(msg.GetByte());
		int unreadBits = msg.UnreadBits;
		msg.GetBits(unreadBits, out byte b);
		message.AddBits(b, unreadBits);
		return message;
	}`

**Comment by Per6** [comment]
#151

**Comment by Per6** [comment]
i guess the `Id` parameter works and the messages simply break in that situation

**Comment by tom-weiland** [comment]
I honestly don't think Riptide needs any more message send modes. Something like a sequenced reliable mode (which I *think* is what this PR is for, but I don't have a ton of time right now to look into it deeply) can be built on top of the existing Reliable or Notify send modes without really modifying the library itself.

Completely new features/somewhat larger scale changes like this would also need to undergo extensive testing before being merged, plus it would likely require further work/bug fixes afterwards—I'm no longer actively working on the library so this is not something I can do.

As for the property that returns the message ID, merging that doesn't make too much sense either as if I was still working on Riptide, I would be moving towards removing the concept of message IDs entirely from the core library. Message IDs aren't necessary in a lot of cases (which is why the Notify send mode already doesn't have them built in) and can get in the way, and if you *do* need them it's easy to add them yourself just like any other data (doesn't require any modifications to Riptide's source).

---

Also for future reference, please follow the [contribution guidelines](https://github.com/RiptideNetworking/Riptide/blob/main/CONTRIBUTING.md), specifically the point about keeping pull requests focused on one issue/feature (whenever possible) and the commit message formatting guidelines.

---

> for some reason some messages recieved by the server give the wrong id, so it isnt finished quite yet
>
> Creating a new message, pushing all the data into that one and then sending that seems to not have that problem.
I have no idea how that happens???

See my explanation in #151.

**Comment by Per6** [comment]
I've improved, fixed and tested the queued send mode in my fork.
I think it would fit nicely into riptide. I could also do more tests if there is something i still need to test for.
(my projects and stress tests were fine)
Message ID's are practical in almost all situations, so them not being necessary doesn't mean much.

**Comment by tom-weiland** [comment]
As I explained in issue #152, you should be able to quite easily implement this "send mode" on top of the existing Notify send mode without modifying Riptide itself, and it would even be more data/bandwidth-efficient because you don't have to repeatedly resend the last message in case it was lost, you can simply wait for Notify to tell you if it was lost or delivered and then proceed accordingly.

> Message ID's are practical in almost all situations, so them not being necessary doesn't mean much.

Maybe as long as you're doing all data synchronization by setting up messages manually, but that's a lot of work and not ideal for anything other than small projects. If you build a higher level/automatic replication layer on top of Riptide you will not need more than 5 different message types, which you could fit into 3 bits if you as the developer handled message IDs yourself instead of Riptide forcing you to use a ushort (2 bytes/16 bits).

Even if they were practical in the majority of situations, Riptide would be more flexible if it did not have a concept of message IDs and didn't impose that on everyone. Especially considering how, again, message IDs are *very* easy to add yourself on top of Riptide.

**Comment by Per6** [comment]
A send mode should definitely belong in riptide, not my project.
I don't quite understand how Notify works but wouldn't it only notify if another message was sent after, which wouldn't fulfill my requirenments of reliable.
For the IDs, riptide could also simply implement a maxId instead of outright removing IDs.
Technically those 5 different message types could also only need log2(6) bits, however that would require a bunch of rewriting of riptide.

**Comment by tom-weiland** [comment]
> I don't quite understand how Notify works but wouldn't it only notify if another message was sent after, which wouldn't fulfill my requirenments of reliable.

I suppose the other end would need to be sending Notify messages in order for you to find out if the one you sent was delivered, I didn't consider that. However having each end send empty Notify messages (if no actual data needs to be sent) would resolve this and would also allow you to more accurately calculate ping and when the other end has timed out/stopped responding, all while costing virtually nothing in terms of bandwidth & CPU time.

> For the IDs, riptide could also simply implement a maxId instead of outright removing IDs.
Technically those 5 different message types could also only need log2(5) bits, however that would require a bunch of rewriting of riptide.

Or it could do neither and just not have message IDs, thereby allowing devs to choose what's most appropriate for their needs and optimize accordingly 😄

Message IDs have absolutely no bearing on what Riptide does with a given message and therefore are (or rather, should be) out of its scope. Why have Riptide define a concept along with its requirements & restrictions when there is no reason for doing so? All it does is impose arbitrary limits on devs.

**Comment by Per6** [comment]
> Or it could do neither and just not have message IDs, thereby allowing devs to choose what's most appropriate for their needs and optimize accordingly 😄

no, they could set the maxId to 0, thereby sending log2(0(maxId) + 1) => 0 extra bits for the messageId. There is no reason to remove a feature, when you can give the option to not use it.

**Comment by tom-weiland** [comment]
> no, they could set the maxId to 0, thereby sending log2(0(maxId) + 1) => 0 extra bits for the messageId.

Then you still have the overhead of that even though it does nothing, and it requires setting/specifying another setting.

> There is no reason to remove a feature, when you can give the option to not use it.

If you ask me, applying this mindset to features like this which
- don't affect how the library works,
- aren't necessary in many cases, and
- are extremely easy to implement yourself if you do need them,

is how you end up with bloated codebases 🤷‍♂️

**Comment by Per6** [comment]
I've taken inspiration from Notify and modified the queued send mode. It is now both a bit more data/bandwidth efficient and a bit less data/time efficient, compared to using Notify.

**Pull request closed without merging**
